import { useState, useEffect } from "react";
import styles from "./Ranking.module.css";

export default function Ranking() {
  const [user, setUser] = useState([
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 2,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 3,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 4,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 5,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 6,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 7,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 8,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 9,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 10,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 11,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
  ]);
  const [page, setPage] = useState(1);
  const [lenArr, setLenArr] = useState([]);
  useEffect(() => {
    setLenArr([...Array(parseInt(user.length / 10) + 1).keys()]);
  }, [page]);
  return (
    <div className={styles.main}>
      <div className={styles.h1}>
        <h1>Ranking</h1>
      </div>
      <div className={styles.container}>
        <div className={styles.articles}>
          <div className={styles.att}>
            <div>Rank</div>
            <div>Summoner</div>
            <div>Tier</div>
            <div>LP</div>
            <div>Most Champion</div>
            <div>Win Rate</div>
          </div>
          {user
            .filter((num, idx) => {
              return parseInt(idx / 10) + 1 === page ? num : null;
            })
            .map((user, idx) => {
              return (
                <div key={idx} className={styles.article}>
                  <div>{user.rank}</div>
                  <div>{user.summoner}</div>
                  <div>{user.tier}</div>
                  <div>{user.lp}</div>
                  <div className={styles.imgs}>
                    <img
                      src={`/champion/tiles/${user.mostChampion[0]}_0.jpg`}
                      className={styles.img}
                    ></img>
                    <img
                      src={`/champion/tiles/${user.mostChampion[1]}_0.jpg`}
                      className={styles.img}
                    ></img>
                    <img
                      src={`/champion/tiles/${user.mostChampion[2]}_0.jpg`}
                      className={styles.img}
                    ></img>
                  </div>
                  <div>{user.winRate}</div>
                </div>
              );
            })}
        </div>
      </div>
      <div className={styles.buttons}>
        {lenArr.map((num, idx) => {
          return (
            <div key={idx}>
              <button
                className={styles.button}
                onClick={(e) => {
                  setPage(Number(e.target.innerText));
                }}
              >
                {num + 1}
              </button>
            </div>
          );
        })}
      </div>
    </div>
  );
}
