export default function championList() {
  const championlist = [
    {
      Q: "GarenQ",
      W: "GarenW",
      E: "GarenE",
      R: "GarenR",
      index: 0,
      ko: "가렌",
      en: "Garen",
    },
    {
      Q: "GalioQ",
      W: "GalioW",
      E: "GalioE",
      R: "GalioR",
      index: 1,
      ko: "갈리오",
      en: "Galio",
    },
    {
      Q: "GangplankQWrapper",
      W: "GangplankW",
      E: "GangplankE",
      R: "GangplankR",
      index: 2,
      ko: "갱플랭크",
      en: "Gangplank",
    },
    {
      Q: "GragasQ",
      W: "GragasW",
      E: "GragasE",
      R: "GragasR",
      index: 3,
      ko: "그라가스",
      en: "Gragas",
    },
    {
      Q: "GravesQLineSpell",
      W: "GravesSmokeGrenade",
      E: "GravesMove",
      R: "GravesChargeShot",
      index: 4,
      ko: "그레이브즈",
      en: "Graves",
    },
    {
      Q: "GwenQ",
      W: "GwenW",
      E: "GwenE",
      R: "GwenR",
      index: 5,
      ko: "그웬",
      en: "Gwen",
    },
    {
      Q: "GnarQ",
      W: "GnarW",
      E: "GnarE",
      R: "GnarR",
      index: 6,
      ko: "나르",
      en: "Gnar",
    },
    {
      Q: "NamiQ",
      W: "NamiW",
      E: "NamiE",
      R: "NamiR",
      index: 7,
      ko: "나미",
      en: "Nami",
    },
    {
      Q: "NasusQ",
      W: "NasusW",
      E: "NasusE",
      R: "NasusR",
      index: 8,
      ko: "나서스",
      en: "Nasus",
    },
    {
      Q: "NautilusAnchorDrag",
      W: "NautilusPiercingGaze",
      E: "NautilusSplashZone",
      R: "NautilusGrandLine",
      index: 9,
      ko: "노틸러스",
      en: "Nautilus",
    },
    {
      Q: "NocturneDuskbringer",
      W: "NocturneShroudofDarkness",
      E: "NocturneUnspeakableHorror",
      R: "NocturneParanoia",
      index: 10,
      ko: "녹턴",
      en: "Nocturne",
    },
    {
      Q: "NunuQ",
      W: "NunuW",
      E: "NunuE",
      R: "NunuR",
      index: 11,
      ko: "누누와 윌럼프",
      en: "Nunu",
    },
    {
      Q: "JavelinToss",
      W: "Bushwhack",
      E: "PrimalSurge",
      R: "AspectOfTheCougar",
      index: 12,
      ko: "니달리",
      en: "Nidalee",
    },
    {
      Q: "NeekoQ",
      W: "NeekoW",
      E: "NeekoE",
      R: "NeekoR",
      index: 13,
      ko: "니코",
      en: "Neeko",
    },
    {
      Q: "NilahQ",
      W: "NilahW",
      E: "NilahE",
      R: "NilahR",
      index: 14,
      ko: "닐라",
      en: "Nilah",
    },
    {
      Q: "DariusCleave",
      W: "DariusNoxianTacticsONH",
      E: "DariusAxeGrabCone",
      R: "DariusExecute",
      index: 15,
      ko: "다리우스",
      en: "Darius",
    },
    {
      Q: "DianaQ",
      W: "DianaOrbs",
      E: "DianaTeleport",
      R: "DianaR",
      index: 16,
      ko: "다이애나",
      en: "Diana",
    },
    {
      Q: "DravenSpinning",
      W: "DravenFury",
      E: "DravenDoubleShot",
      R: "DravenRCast",
      index: 17,
      ko: "드레이븐",
      en: "Draven",
    },
    {
      Q: "RyzeQWrapper",
      W: "RyzeW",
      E: "RyzeE",
      R: "RyzeR",
      index: 18,
      ko: "라이즈",
      en: "Ryze",
    },
    {
      Q: "RakanQ",
      W: "RakanW",
      E: "RakanE",
      R: "RakanR",
      index: 19,
      ko: "라칸",
      en: "Rakan",
    },
    {
      Q: "PowerBall",
      W: "DefensiveBallCurl",
      E: "PuncturingTaunt",
      R: "Tremors2",
      index: 20,
      ko: "람머스",
      en: "Rammus",
    },
    {
      Q: "LuxLightBinding",
      W: "LuxPrismaticWave",
      E: "LuxLightStrikeKugel",
      R: "LuxR",
      index: 21,
      ko: "럭스",
      en: "Lux",
    },
    {
      Q: "RumbleFlameThrower",
      W: "RumbleShield",
      E: "RumbleGrenade",
      R: "RumbleCarpetBomb",
      index: 22,
      ko: "럼블",
      en: "Rumble",
    },
    {
      Q: "RenataQ",
      W: "RenataW",
      E: "RenataE",
      R: "RenataR",
      index: 23,
      ko: "레나타 글라스크",
      en: "Renata",
    },
    {
      Q: "RenektonCleave",
      W: "RenektonPreExecute",
      E: "RenektonSliceAndDice",
      R: "RenektonReignOfTheTyrant",
      index: 24,
      ko: "레넥톤",
      en: "Renekton",
    },
    {
      Q: "LeonaShieldOfDaybreak",
      W: "LeonaSolarBarrier",
      E: "LeonaZenithBlade",
      R: "LeonaSolarFlare",
      index: 25,
      ko: "레오나",
      en: "Leona",
    },
    {
      Q: "RekSaiQ",
      W: "RekSaiW",
      E: "RekSaiE",
      R: "RekSaiRWrapper",
      index: 26,
      ko: "렉사이",
      en: "RekSai",
    },
    {
      Q: "RellQ",
      W: "RellW_Dismount",
      E: "RellE",
      R: "RellR",
      index: 27,
      ko: "렐",
      en: "Rell",
    },
    {
      Q: "RengarQ",
      W: "RengarW",
      E: "RengarE",
      R: "RengarR",
      index: 28,
      ko: "렝가",
      en: "Rengar",
    },
    {
      Q: "LucianQ",
      W: "LucianW",
      E: "LucianE",
      R: "LucianR",
      index: 29,
      ko: "루시안",
      en: "Lucian",
    },
    {
      Q: "LuluQ",
      W: "LuluW",
      E: "LuluE",
      R: "LuluR",
      index: 30,
      ko: "룰루",
      en: "Lulu",
    },
    {
      Q: "LeblancQ",
      W: "LeblancW",
      E: "LeblancE",
      R: "LeblancR",
      index: 31,
      ko: "르블랑",
      en: "Leblanc",
    },
    {
      Q: "BlindMonkQOne",
      W: "BlindMonkWOne",
      E: "BlindMonkEOne",
      R: "BlindMonkRKick",
      index: 32,
      ko: "리신",
      en: "LeeSin",
    },
    {
      Q: "RivenTriCleave",
      W: "RivenMartyr",
      E: "RivenFeint",
      R: "RivenFengShuiEngine",
      index: 33,
      ko: "리븐",
      en: "Riven",
    },
    {
      Q: "LissandraQ",
      W: "LissandraW",
      E: "LissandraE",
      R: "LissandraR",
      index: 34,
      ko: "리산드라",
      en: "Lissandra",
    },
    {
      Q: "LilliaQ",
      W: "LilliaW",
      E: "LilliaE",
      R: "LilliaR",
      index: 35,
      ko: "릴리아",
      en: "Lillia",
    },
    {
      Q: "AlphaStrike",
      W: "Meditate",
      E: "WujuStyle",
      R: "Highlander",
      index: 36,
      ko: "마스터 이",
      en: "MasterYi",
    },
    {
      Q: "MaokaiQ",
      W: "MaokaiW",
      E: "MaokaiE",
      R: "MaokaiR",
      index: 37,
      ko: "마오카이",
      en: "Maokai",
    },
    {
      Q: "MalzaharQ",
      W: "MalzaharW",
      E: "MalzaharE",
      R: "MalzaharR",
      index: 38,
      ko: "말자하",
      en: "Malzahar",
    },
    {
      Q: "SeismicShard",
      W: "Obduracy",
      E: "Landslide",
      R: "UFSlash",
      index: 39,
      ko: "말파이트",
      en: "Malphite",
    },
    {
      Q: "MordekaiserQ",
      W: "MordekaiserW",
      E: "MordekaiserE",
      R: "MordekaiserR",
      index: 40,
      ko: "모데카이저",
      en: "Mordekaiser",
    },
    {
      Q: "MorganaQ",
      W: "MorganaW",
      E: "MorganaE",
      R: "MorganaR",
      index: 41,
      ko: "모르가나",
      en: "Morgana",
    },
    {
      Q: "DrMundoQ",
      W: "DrMundoW",
      E: "DrMundoE",
      R: "DrMundoR",
      index: 42,
      ko: "문도 박사",
      en: "DrMundo",
    },
    {
      Q: "MissFortuneRicochetShot",
      W: "MissFortuneViciousStrikes",
      E: "MissFortuneScattershot",
      R: "MissFortuneBulletTime",
      index: 43,
      ko: "미스 포츈",
      en: "MissFortune",
    },
    {
      Q: "BardQ",
      W: "BardW",
      E: "BardE",
      R: "BardR",
      index: 44,
      ko: "바드",
      en: "Bard",
    },
    {
      Q: "VarusQ",
      W: "VarusW",
      E: "VarusE",
      R: "VarusR",
      index: 45,
      ko: "바루스",
      en: "Varus",
    },
    { Q: "ViQ", W: "ViW", E: "ViE", R: "ViR", index: 46, ko: "바이", en: "Vi" },
    {
      Q: "VeigarBalefulStrike",
      W: "VeigarDarkMatter",
      E: "VeigarEventHorizon",
      R: "VeigarR",
      index: 47,
      ko: "베이가",
      en: "Veigar",
    },
    {
      Q: "VayneTumble",
      W: "VayneSilveredBolts",
      E: "VayneCondemn",
      R: "VayneInquisition",
      index: 48,
      ko: "베인",
      en: "Vayne",
    },
    {
      Q: "VexQ",
      W: "VexW",
      E: "VexE",
      R: "VexR",
      index: 49,
      ko: "벡스",
      en: "Vex",
    },
    {
      Q: "BelvethQ",
      W: "BelvethW",
      E: "BelvethE",
      R: "BelvethR",
      index: 50,
      ko: "벨베스",
      en: "Belveth",
    },
    {
      Q: "VelkozQ",
      W: "VelkozW",
      E: "VelkozE",
      R: "VelkozR",
      index: 51,
      ko: "벨코즈",
      en: "Velkoz",
    },
    {
      Q: "VolibearQ",
      W: "VolibearW",
      E: "VolibearE",
      R: "VolibearR",
      index: 52,
      ko: "볼리베어",
      en: "Volibear",
    },
    {
      Q: "BraumQ",
      W: "BraumW",
      E: "BraumE",
      R: "BraumRWrapper",
      index: 53,
      ko: "브라움",
      en: "Braum",
    },
    {
      Q: "BrandQ",
      W: "BrandW",
      E: "BrandE",
      R: "BrandR",
      index: 54,
      ko: "브랜드",
      en: "Brand",
    },
    {
      Q: "VladimirQ",
      W: "VladimirSanguinePool",
      E: "VladimirE",
      R: "VladimirHemoplague",
      index: 55,
      ko: "블라디미르",
      en: "Vladimir",
    },
    {
      Q: "RocketGrab",
      W: "Overdrive",
      E: "PowerFist",
      R: "StaticField",
      index: 56,
      ko: "블리츠크랭크",
      en: "Blitzcrank",
    },
    {
      Q: "ViegoQ",
      W: "ViegoW",
      E: "ViegoE",
      R: "ViegoR",
      index: 57,
      ko: "비에고",
      en: "Viego",
    },
    {
      Q: "ViktorPowerTransfer",
      W: "ViktorGravitonField",
      E: "ViktorDeathRay",
      R: "ViktorChaosStorm",
      index: 58,
      ko: "빅토르",
      en: "Viktor",
    },
    {
      Q: "PoppyQ",
      W: "PoppyW",
      E: "PoppyE",
      R: "PoppyR",
      index: 59,
      ko: "뽀삐",
      en: "Poppy",
    },
    {
      Q: "SamiraQ",
      W: "SamiraW",
      E: "SamiraE",
      R: "SamiraR",
      index: 60,
      ko: "사미라",
      en: "Samira",
    },
    {
      Q: "SionQ",
      W: "SionW",
      E: "SionE",
      R: "SionR",
      index: 61,
      ko: "사이온",
      en: "Sion",
    },
    {
      Q: "SylasQ",
      W: "SylasW",
      E: "SylasE",
      R: "SylasR",
      index: 62,
      ko: "사일러스",
      en: "Sylas",
    },
    {
      Q: "Deceive",
      W: "JackInTheBox",
      E: "TwoShivPoison",
      R: "HallucinateFull",
      index: 63,
      ko: "샤코",
      en: "Shaco",
    },
    {
      Q: "SennaQ",
      W: "SennaW",
      E: "SennaE",
      R: "SennaR",
      index: 64,
      ko: "세나",
      en: "Senna",
    },
    {
      Q: "SeraphineQ",
      W: "SeraphineW",
      E: "SeraphineE",
      R: "SeraphineR",
      index: 65,
      ko: "세라핀",
      en: "Seraphine",
    },
    {
      Q: "SejuaniQ",
      W: "SejuaniW",
      E: "SejuaniE",
      R: "SejuaniR",
      index: 66,
      ko: "세주아니",
      en: "Sejuani",
    },
    {
      Q: "SettQ",
      W: "SettW",
      E: "SettE",
      R: "SettR",
      index: 67,
      ko: "세트",
      en: "Sett",
    },
    {
      Q: "SonaQ",
      W: "SonaW",
      E: "SonaE",
      R: "SonaR",
      index: 68,
      ko: "소나",
      en: "Sona",
    },
    {
      Q: "SorakaQ",
      W: "SorakaW",
      E: "SorakaE",
      R: "SorakaR",
      index: 69,
      ko: "소라카",
      en: "Soraka",
    },
    {
      Q: "ShenQ",
      W: "ShenW",
      E: "ShenE",
      R: "ShenR",
      index: 70,
      ko: "쉔",
      en: "Shen",
    },
    {
      Q: "ShyvanaDoubleAttack",
      W: "ShyvanaImmolationAura",
      E: "ShyvanaFireball",
      R: "ShyvanaTransformCast",
      index: 71,
      ko: "쉬바나",
      en: "Shyvana",
    },
    {
      Q: "SwainQ",
      W: "SwainW",
      E: "SwainE",
      R: "SwainR",
      index: 72,
      ko: "스웨인",
      en: "Swain",
    },
    {
      Q: "SkarnerVirulentSlash",
      W: "SkarnerExoskeleton",
      E: "SkarnerFracture",
      R: "SkarnerImpale",
      index: 73,
      ko: "스카너",
      en: "Skarner",
    },
    {
      Q: "SivirQ",
      W: "SivirW",
      E: "SivirE",
      R: "SivirR",
      index: 74,
      ko: "시비르",
      en: "Sivir",
    },
    {
      Q: "XinZhaoQ",
      W: "XinZhaoW",
      E: "XinZhaoE",
      R: "XinZhaoR",
      index: 75,
      ko: "신 짜오",
      en: "XinZhao",
    },
    {
      Q: "SyndraQ",
      W: "SyndraW",
      E: "SyndraE",
      R: "SyndraR",
      index: 76,
      ko: "신드라",
      en: "Syndra",
    },
    {
      Q: "PoisonTrail",
      W: "MegaAdhesive",
      E: "Fling",
      R: "InsanityPotion",
      index: 77,
      ko: "신지드",
      en: "Singed",
    },
    {
      Q: "ThreshQ",
      W: "ThreshW",
      E: "ThreshE",
      R: "ThreshRPenta",
      index: 78,
      ko: "쓰레쉬",
      en: "Thresh",
    },
    {
      Q: "AhriOrbofDeception",
      W: "AhriFoxFire",
      E: "AhriSeduce",
      R: "AhriTumble",
      index: 79,
      ko: "아리",
      en: "Ahri",
    },
    {
      Q: "BandageToss",
      W: "AuraofDespair",
      E: "Tantrum",
      R: "CurseoftheSadMummy",
      index: 80,
      ko: "아무무",
      en: "Amumu",
    },
    {
      Q: "AurelionSolQ",
      W: "AurelionSolW",
      E: "AurelionSolE",
      R: "AurelionSolR",
      index: 81,
      ko: "아우렐리온 솔",
      en: "AurelionSol",
    },
    {
      Q: "IvernQ",
      W: "IvernW",
      E: "IvernE",
      R: "IvernR",
      index: 82,
      ko: "아이번",
      en: "Ivern",
    },
    {
      Q: "AzirQWrapper",
      W: "AzirW",
      E: "AzirEWrapper",
      R: "AzirR",
      index: 83,
      ko: "아지르",
      en: "Azir",
    },
    {
      Q: "AkaliQ",
      W: "AkaliW",
      E: "AkaliE",
      R: "AkaliR",
      index: 84,
      ko: "아칼리",
      en: "Akali",
    },
    {
      Q: "AkshanQ",
      W: "AkshanW",
      E: "AkshanE",
      R: "AkshanR",
      index: 85,
      ko: "아크샨",
      en: "Akshan",
    },
    {
      Q: "AatroxQ",
      W: "AatroxW",
      E: "AatroxE",
      R: "AatroxR",
      index: 86,
      ko: "아트록스",
      en: "Aatrox",
    },
    {
      Q: "ApheliosQ_ClientTooltipWrapper",
      W: "ApheliosW",
      E: "ApheliosE_ClientTooltipWrapper",
      R: "ApheliosR",
      index: 87,
      ko: "아펠리오스",
      en: "Aphelios",
    },
    {
      Q: "Pulverize",
      W: "Headbutt",
      E: "AlistarE",
      R: "FerociousHowl",
      index: 88,
      ko: "알리스타",
      en: "Alistar",
    },
    {
      Q: "AnnieQ",
      W: "AnnieW",
      E: "AnnieE",
      R: "AnnieR",
      index: 89,
      ko: "애니",
      en: "Annie",
    },
    {
      Q: "FlashFrost",
      W: "Crystallize",
      E: "Frostbite",
      R: "GlacialStorm.png",
      index: 90,
      ko: "애니비아",
      en: "Anivia",
    },
    {
      Q: "AsheQ",
      W: "Volley",
      E: "AsheSpiritOfTheHawk",
      R: "EnchantedCrystalArrow",
      index: 91,
      ko: "애쉬",
      en: "Ashe",
    },
    {
      Q: "YasuoQ1Wrapper",
      W: "YasuoW",
      E: "YasuoE",
      R: "YasuoR",
      index: 92,
      ko: "야스오",
      en: "Yasuo",
    },
    {
      Q: "EkkoQ",
      W: "EkkoW",
      E: "EkkoE",
      R: "EkkoR",
      index: 93,
      ko: "에코",
      en: "Ekko",
    },
    {
      Q: "EliseHumanQ",
      W: "EliseHumanW",
      E: "EliseHumanE",
      R: "EliseR",
      index: 94,
      ko: "엘리스",
      en: "Elise",
    },
    {
      Q: "MonkeyKingDoubleAttack",
      W: "MonkeyKingDecoy",
      E: "MonkeyKingNimbus",
      R: "MonkeyKingSpinToWin",
      index: 95,
      ko: "오공",
      en: "MonkeyKing",
    },
    {
      Q: "OrnnQ",
      W: "OrnnW",
      E: "OrnnE",
      R: "OrnnR",
      index: 96,
      ko: "오른",
      en: "Ornn",
    },
    {
      Q: "OrianaIzunaCommand",
      W: "OrianaDissonanceCommand",
      E: "OrianaRedactCommand",
      R: "OrianaDetonateCommand",
      index: 97,
      ko: "오리아나",
      en: "Orianna",
    },
    {
      Q: "OlafAxeThrowCast",
      W: "OlafFrenziedStrikes",
      E: "OlafRecklessStrike",
      R: "OlafRagnarok",
      index: 98,
      ko: "올라프",
      en: "Olaf",
    },
    {
      Q: "YoneQ",
      W: "YoneW",
      E: "YoneE",
      R: "YoneR",
      index: 99,
      ko: "요네",
      en: "Yone",
    },
    {
      Q: "YorickQ",
      W: "YorickW",
      E: "YorickE",
      R: "YorickR",
      index: 100,
      ko: "요릭",
      en: "Yorick",
    },
    {
      Q: "UdyrQ",
      W: "UdyrW",
      E: "UdyrE",
      R: "UdyrR",
      index: 101,
      ko: "우디르",
      en: "Udyr",
    },
    {
      Q: "UrgotQ",
      W: "UrgotW",
      E: "UrgotE",
      R: "UrgotR",
      index: 102,
      ko: "우르곳",
      en: "Urgot",
    },
    {
      Q: "WarwickQ",
      W: "WarwickW",
      E: "WarwickE",
      R: "WarwickR",
      index: 103,
      ko: "워윅",
      en: "Warwick",
    },
    {
      Q: "YuumiQ",
      W: "YuumiW",
      E: "YuumiE",
      R: "YuumiR",
      index: 104,
      ko: "유미",
      en: "Yuumi",
    },
    {
      Q: "IreliaQ",
      W: "IreliaW",
      E: "IreliaE",
      R: "IreliaR",
      index: 105,
      ko: "이렐리아",
      en: "Irelia",
    },
    {
      Q: "EvelynnQ",
      W: "EvelynnW",
      E: "EvelynnE",
      R: "EvelynnR",
      index: 106,
      ko: "이블린",
      en: "Evelynn",
    },
    {
      Q: "EzrealQ",
      W: "EzrealW",
      E: "EzrealE",
      R: "EzrealR",
      index: 107,
      ko: "이즈리얼",
      en: "Ezreal",
    },
    {
      Q: "IllaoiQ",
      W: "IllaoiW",
      E: "IllaoiE",
      R: "IllaoiR",
      index: 108,
      ko: "일라오이",
      en: "Illaoi",
    },
    {
      Q: "JarvanIVDragonStrike",
      W: "JarvanIVGoldenAegis",
      E: "JarvanIVDemacianStandard",
      R: "JarvanIVCataclysm",
      index: 109,
      ko: "자르반 4세",
      en: "JarvanIV",
    },
    {
      Q: "XayahQ",
      W: "XayahW",
      E: "XayahE",
      R: "XayahR",
      index: 110,
      ko: "자야",
      en: "Xayah",
    },
    {
      Q: "ZyraQ",
      W: "ZyraW",
      E: "ZyraE",
      R: "ZyraR",
      index: 111,
      ko: "자이라",
      en: "Zyra",
    },
    {
      Q: "ZacQ",
      W: "ZacW",
      E: "ZacE",
      R: "ZacR",
      index: 112,
      ko: "자크",
      en: "Zac",
    },
    {
      Q: "HowlingGale",
      W: "SowTheWind",
      E: "EyeOfTheStorm",
      R: "ReapTheWhirlwind",
      index: 113,
      ko: "잔나",
      en: "Janna",
    },
    {
      Q: "JaxLeapStrike",
      W: "JaxEmpowerTwo",
      E: "JaxCounterStrike",
      R: "JaxRelentlessAssault",
      index: 114,
      ko: "잭스",
      en: "Jax",
    },
    {
      Q: "ZedQ",
      W: "ZedW",
      E: "ZedE",
      R: "ZedR",
      index: 115,
      ko: "제드",
      en: "Zed",
    },
    {
      Q: "XerathArcanopulseChargeUp",
      W: "XerathArcaneBarrage2",
      E: "XerathMageSpear",
      R: "XerathLocusOfPower2",
      index: 116,
      ko: "제라스",
      en: "Xerath",
    },
    {
      Q: "ZeriQ",
      W: "ZeriW",
      E: "ZeriE",
      R: "ZeriR",
      index: 117,
      ko: "제리",
      en: "Zeri",
    },
    {
      Q: "JayceToTheSkies",
      W: "JayceStaticField",
      E: "JayceThunderingBlow",
      R: "JayceStanceHtG",
      index: 118,
      ko: "제이스",
      en: "Jayce",
    },
    {
      Q: "ZoeQ",
      W: "ZoeW",
      E: "ZoeE",
      R: "ZoeR",
      index: 119,
      ko: "조이",
      en: "Zoe",
    },
    {
      Q: "ZiggsQ",
      W: "ZiggsW",
      E: "ZiggsE",
      R: "ZiggsR",
      index: 120,
      ko: "직스",
      en: "Ziggs",
    },
    {
      Q: "JhinQ",
      W: "JhinW",
      E: "JhinE",
      R: "JhinR",
      index: 121,
      ko: "진",
      en: "Jhin",
    },
    {
      Q: "ZileanQ",
      W: "ZileanW",
      E: "TimeWarp",
      R: "ChronoShift",
      index: 122,
      ko: "질리언",
      en: "Zilean",
    },
    {
      Q: "JinxQ",
      W: "JinxW",
      E: "JinxE",
      R: "JinxR",
      index: 123,
      ko: "징크스",
      en: "Jinx",
    },
    {
      Q: "Rupture",
      W: "FeralScream",
      E: "VorpalSpikes",
      R: "Feast",
      index: 124,
      ko: "초가스",
      en: "Chogath",
    },
    {
      Q: "KarmaQ",
      W: "KarmaSpiritBind",
      E: "KarmaSolKimShield",
      R: "KarmaMantra",
      index: 125,
      ko: "카르마",
      en: "Karma",
    },
    {
      Q: "CamilleQ",
      W: "CamilleW",
      E: "CamilleE",
      R: "CamilleR",
      index: 126,
      ko: "카밀",
      en: "Camille",
    },
    {
      Q: "NullLance",
      W: "NetherBlade",
      E: "ForcePulse",
      R: "RiftWalk",
      index: 127,
      ko: "카사딘",
      en: "Kassadin",
    },
    {
      Q: "KarthusLayWasteA1",
      W: "KarthusWallOfPain",
      E: "KarthusDefile",
      R: "KarthusFallenOne",
      index: 128,
      ko: "카서스",
      en: "Karthus",
    },
    {
      Q: "CassiopeiaQ",
      W: "CassiopeiaW",
      E: "CassiopeiaE",
      R: "CassiopeiaR",
      index: 129,
      ko: "카시오페아",
      en: "Cassiopeia",
    },
    {
      Q: "KaisaQ",
      W: "KaisaW",
      E: "KaisaE",
      R: "KaisaR",
      index: 130,
      ko: "카이사",
      en: "Kaisa",
    },
    {
      Q: "KhazixQ",
      W: "KhazixW",
      E: "KhazixE",
      R: "KhazixR",
      index: 131,
      ko: "카직스",
      en: "Khazix",
    },
    {
      Q: "KatarinaQ",
      W: "KatarinaW",
      E: "KatarinaEWrapper",
      R: "KatarinaR",
      index: 132,
      ko: "카타리나",
      en: "Katarina",
    },
    {
      Q: "KalistaMysticShot",
      W: "KalistaW",
      E: "KalistaExpungeWrapper",
      R: "KalistaRx",
      index: 133,
      ko: "칼리스타",
      en: "Kalista",
    },
    {
      Q: "KennenShurikenHurlMissile1",
      W: "KennenBringTheLight",
      E: "KennenLightningRush",
      R: "KennenShurikenStorm",
      index: 134,
      ko: "케넨",
      en: "Kennen",
    },
    {
      Q: "CaitlynQ",
      W: "CaitlynW",
      E: "CaitlynE",
      R: "CaitlynR",
      index: 135,
      ko: "케이틀린",
      en: "Caitlyn",
    },
    {
      Q: "KaynQ",
      W: "KaynW",
      E: "KaynE",
      R: "KaynR",
      index: 136,
      ko: "케인",
      en: "Kayn",
    },
    {
      Q: "KayleQ",
      W: "KayleW",
      E: "KayleE",
      R: "KayleR",
      index: 137,
      ko: "케일",
      en: "Kayle",
    },
    {
      Q: "KogMawQ",
      W: "KogMawBioArcaneBarrage",
      E: "KogMawVoidOoze",
      R: "KogMawLivingArtillery",
      index: 138,
      ko: "코그모",
      en: "KogMaw",
    },
    {
      Q: "PhosphorusBomb",
      W: "CarpetBomb",
      E: "GGun",
      R: "MissileBarrage",
      index: 139,
      ko: "코르키",
      en: "Corki",
    },
    {
      Q: "QuinnQ",
      W: "QuinnW",
      E: "QuinnE",
      R: "QuinnR",
      index: 140,
      ko: "퀸",
      en: "Quinn",
    },
    {
      Q: "KledQ",
      W: "KledW",
      E: "KledE",
      R: "KledR",
      index: 141,
      ko: "클레드",
      en: "Kled",
    },
    {
      Q: "QiyanaQ",
      W: "QiyanaW",
      E: "QiyanaE",
      R: "QiyanaR",
      index: 142,
      ko: "키아나",
      en: "Qiyana",
    },
    {
      Q: "KindredQ",
      W: "KindredW",
      E: "KindredEWrapper",
      R: "KindredR",
      index: 143,
      ko: "킨드레드",
      en: "Kindred",
    },
    {
      Q: "TaricQ",
      W: "TaricW",
      E: "TaricE",
      R: "TaricR",
      index: 144,
      ko: "타릭",
      en: "Taric",
    },
    {
      Q: "TalonQ",
      W: "TalonW",
      E: "TalonE",
      R: "TalonR",
      index: 145,
      ko: "탈론",
      en: "Talon",
    },
    {
      Q: "TaliyahQ",
      W: "TaliyahWVC",
      E: "TaliyahE",
      R: "TaliyahR",
      index: 146,
      ko: "탈리야",
      en: "Taliyah",
    },
    {
      Q: "TahmKenchQ",
      W: "TahmKenchW",
      E: "TahmKenchE",
      R: "TahmKenchRWrapper",
      index: 147,
      ko: "탐 켄치",
      en: "TahmKench",
    },
    {
      Q: "TrundleTrollSmash",
      W: "trundledesecrate",
      E: "TrundleCircle",
      R: "TrundlePain",
      index: 148,
      ko: "트런들",
      en: "Trundle",
    },
    {
      Q: "TristanaQ",
      W: "TristanaW",
      E: "TristanaE",
      R: "TristanaR",
      index: 149,
      ko: "트리스타나",
      en: "Tristana",
    },
    {
      Q: "TryndamereQ",
      W: "TryndamereW",
      E: "TryndamereE",
      R: "UndyingRage",
      index: 150,
      ko: "트린다미어",
      en: "Tryndamere",
    },
    {
      Q: "WildCards",
      W: "PickACard",
      E: "CardmasterStack",
      R: "Destiny",
      index: 151,
      ko: "트위스티드 페이트",
      en: "TwistedFate",
    },
    {
      Q: "TwitchHideInShadows",
      W: "TwitchVenomCask",
      E: "TwitchExpunge",
      R: "TwitchFullAutomatic",
      index: 152,
      ko: "트위치",
      en: "Twitch",
    },
    {
      Q: "BlindingDart",
      W: "MoveQuick",
      E: "ToxicShot",
      R: "TeemoRCast",
      index: 153,
      ko: "티모",
      en: "Teemo",
    },
    {
      Q: "PykeQ",
      W: "PykeW",
      E: "PykeE",
      R: "PykeR",
      index: 154,
      ko: "파이크",
      en: "Pyke",
    },
    {
      Q: "PantheonQ",
      W: "PantheonW",
      E: "PantheonE",
      R: "PantheonR",
      index: 155,
      ko: "판테온",
      en: "Pantheon",
    },
    {
      Q: "FiddleSticksQ",
      W: "FiddleSticksW",
      E: "FiddleSticksE",
      R: "FiddleSticksR",
      index: 156,
      ko: "피들스틱",
      en: "Fiddlesticks",
    },
    {
      Q: "FioraQ",
      W: "FioraW",
      E: "FioraE",
      R: "FioraR",
      index: 157,
      ko: "피오라",
      en: "Fiora",
    },
    {
      Q: "FizzQ",
      W: "FizzW",
      E: "FizzE",
      R: "FizzR",
      index: 158,
      ko: "피즈",
      en: "Fizz",
    },
    {
      Q: "HeimerdingerQ",
      W: "HeimerdingerW",
      E: "HeimerdingerE",
      R: "HeimerdingerR",
      index: 159,
      ko: "하이머딩거",
      en: "Heimerdinger",
    },
    {
      Q: "HecarimRapidSlash",
      W: "HecarimW",
      E: "HecarimRamp",
      R: "HecarimUlt",
      index: 160,
      ko: "헤카림",
      en: "Hecarim",
    },
  ];
  return championlist;
}
