export default function ranking() {
  return [
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 2,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 3,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 4,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 5,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 6,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 7,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 8,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 9,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 10,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 11,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
    {
      rank: 1,
      summoner: "viper3",
      tier: "Challenger",
      lp: "1,726LP",
      mostChampion: ["Jhin", "Jinx", "Kaisa"],
      winRate: 50,
    },
  ];
}
