export default function region() {
  return [
    {
      name: "밴들시티",
      champions: ["Corki", "Lulu", "Rumble", "Teemo", "Tristana", "Veigar", "Yuumi"],
      ko: ["코르키", "룰루", "럼블", "티모", "트리스타나", "베이가", "유미"],
      story: "요들의 고향이 정확히 어디에 있는지에 대해서는 여러 가지 설이 있지만, 몇몇 사람들은 보이지 않는 차원문을 여러 개 통과해야 도달할 수 있는, 물질 세계의 영역을 넘어 신비로운 마법이 깃든 땅을 언급한다. 그곳은 제약 없이 자유로이 마법을 사용할 수 있기 때문에, 앞뒤 가리지 않고 뛰어들었다가는 그 끝없는 경이로움에 사로잡힌 나머지 결국 꿈속에 깊이 빠져들어 버리고 만다는 것이다...",
      icon: "/rigeon_icon/bandle_city_crest_icon.png",
      video: "/rigeon_video/bandle-city-splashvideo.webm",
    },
    {
      name: "빌지워터",
      champions: ["Fizz", "Gangplank", "Graves", "Illaoi", "MissFortune", "Nautilus", "Pyke", "TahmKench", "TwistedFate"],
      ko: ["피즈", "갱플랭크", "그레이브즈", "일라오이", "미스 포츈", "노틸러스", "파이크", "탐켄치", "트위스티드 페이트"],
      story: "푸른 불꽃 제도에 위치한 빌지워터는 다른 항구 도시와는 다릅니다. 바다뱀 사냥꾼, 부두 건달, 밀수업자가 모여드는 이곳에서는 어마어마한 부와 야망도 눈 깜짝할 새에 사라지고 말죠. 그 누구도 다른 사람의 과거에 관심이 없기 때문에 법의 심판, 빚, 박해를 피해 도망쳐온 사람들이 새로운 시작을 꿈꿀 수 있는 곳이기도 합니다. 그렇기는 해도 매일 새벽 부둣가에는 지갑을 털린 채 목숨을 잃은 부주의한 여행자들이 발견됩니다...",
      icon: "/rigeon_icon/bilgewater_crest_icon.png",
      video: "/rigeon_video/bilgewater-splashvideo.webm",
    },
    {
      name: "데마시아",
      champions: ["Fiora", "Galio", "Garen", "JarvanIV", "Kayle", "Lucian", "Lux", "Morgana", "Poppy", "Quinn", "Shyvana", "Sona", "Sylas", "Vayne", "XinZhao"],
      ko: ["피오라", "갈리오", "가렌", "자르반IV", "케일", "루시안", "럭스", "모르가나", "뽀삐", "퀸", "쉬바나", "소나", "사일러스", "베인", "신 짜오"],
      story: "명망 높은 역사의 군대를 지닌 강력하고 질서 잡힌 왕국, 데마시아의 백성들은 언제나 정의와 명예, 의무를 가장 고귀한 것으로 여기며 자국의 문화유산을 자랑스러워했다. 하지만 이런 고상한 신념에도 불구하고, 이 자급자족 국가는 최근 몇 세기 동안 점점 고립되어 가고 있었다.",
      icon: "/rigeon_icon/demacia_crest_icon.png",
      video: "/rigeon_video/demacia-splashvideo.webm",
    },
    {
      name: "아이오니아",
      champions: ["Ahri", "Akali", "Irelia", "Ivern", "Jhin", "Karma", "Kayn", "Kennen", "LeeSin", "Lillia", "MasterYi", "MonkeyKing", "Rakan", "Sett", "Shen", "Syndra", "Varus", "Xayah", "Yasuo", "Yone", "Zed"],
      ko: ["아리", "아칼리", "이렐리아", "아이번", "진", "카르마", "케인", "케넨", "리신", "릴리아", "마스터 이", "오공", "라칸", "세트", "쉔", "신드라", "바루스", "자야", "야스오", "요네", "제드"],
      story: "험난한 바다로 둘러싸인 아이오니아는 최초의 땅이라 불리는 거대한 군도에 흩어져 있는 여러 지방의 연합입니다. 아이오니아 문화는 오랫동안 모든 것의 균형을 추구해 왔기 때문에 물질 세계와 영혼 세계의 경계가 얇으며, 야생 숲과 산중에서는 그 경향이 더욱 두드러집니다.",
      icon: "/rigeon_icon/ionia_crest_icon.png",
      video: "/rigeon_video/ionia-splashvideo.webm",
    },
    {
      name: "익쉬탈",
      champions: ["Malphite", "Neeko", "Nidalee", "Qiyana", "Rengar", "Zyra"],
      ko: ["말파이트", "니코", "니달리", "키아나", "렝가", "자이라"],
      story: "원소 마법으로 유명한 이쉬탈은 가장 먼저 슈리마 제국에 합류한 독립국 중 하나이다. 사실 이쉬탈 문화는 슈리마보다 훨씬 오래된 것으로 부흐루, 장엄한 헬리아, 금욕주의적인 타곤 등의 문명 형성에 영향을 미친 서부 이주민 문화의 일부다. 최초의 초월체 탄생에 큰 역할을 했을 가능성이 높다.",
      icon: "/rigeon_icon/ixtal_crest_icon.png",
      video: "/rigeon_video/ixtal-splashvideo.webm",
    },
    {
      name: "녹서스",
      champions: ["Cassiopeia", "Darius", "Draven", "Katarina", "Kled", "Leblanc", "Mordekaiser", "Riven", "Samira", "Sion", "Swain", "Talon", "Vladimir"],
      ko: ["카시오페아", "다리우스", "드레이븐", "카타리나", "클레드", "르블랑", "모데카이저", "리븐", "사미라", "사이온", "스웨인", "탈론", "블라디미르"],
      story: "녹서스는 악명을 널리 떨치는 강력한 제국입니다. 다른 나라에 살고 있는 이들에게 녹서스는 폭력적이고 침략을 일삼는 위험한 나라이지만, 바깥에서 보이는 호전성을 잠시 접어 두고 안을 들여다보면 특이할 정도로 포용적인 사회를 발견할 수 있습니다. 이 나라에선 모든 국민의 강점과 재능을 존중하고 계발해 주기 때문입니다.",
      icon: "/rigeon_icon/noxus_crest_icon.png",
      video: "/rigeon_video/noxus-splashvideo.webm",
    },
    {
      name: "필트오버",
      champions: ["Caitlyn", "Camille", "Ezreal", "Heimerdinger", "Jayce", "Orianna", "Seraphine", "Vi"],
      ko: ["케이틀린", "카밀", "이즈리얼", "하이머딩거", "제이스", "오리아나", "세라핀", "바이"],
      story: "필트오버는 번영을 누리는 진보적인 도시로, 갈수록 그 영향력이 증대해가고 있다. 이곳은 발로란의 문화적 중심지로, 예술과 기술, 상업과 혁신이 서로 맞물리며 발전해나가는 장소이기도 하다. 필트오버의 저력은 군사력이 아니라 상업의 활력과 진취적인 사고에서 나온다. 바다가 내려다보이는 자운 위의 절벽에 자리잡은 필트오버에는 거대한 수문으로 배들이 수없이 드나들며 전세계에서 상품을 실어나른다.",
      icon: "/rigeon_icon/piltover_crest_icon.png",
      video: "/rigeon_video/piltover-splashvideo.webm",
    },
    {
      name: "그림자 군도",
      champions: ["Elise", "Gwen", "Hecarim", "Kalista", "Karthus", "Maokai", "Thresh", "Vex", "Viego", "Yorick"],
      ko: ["엘리스", "그웬", "헤카림", "칼리스타", "카서스", "마오카이", "쓰레쉬", "벡스", "비에고", "요릭"],
      story: "과거 동맹국들과 사절들이 축복의 빛 군도로 불렀던 이곳은 한때 고결하고 현명한 문명이 자리 잡기도 했지만, 지금은 저주받은 땅이 되어 버렸습니다. 약 천 년 전, 마법으로 인해 전례 없는 대재앙이 발생하면서 물질 세계와 영혼 세계 사이의 장벽이 파괴되었고, 이로 인해 두 세계가 합쳐지면서 모든 생명이 순식간에 파멸을 맞았죠.",
      icon: "/rigeon_icon/shadow_isles_crest_icon.png",
      video: "/rigeon_video/shadow-isles-splashvideo.webm",
    },
    {
      name: "슈리마",
      champions: ["Akshan", "Amumu", "Azir", "Nasus", "Rammus", "Renekton", "Rengar", "Sivir", "Skarner", "Taliyah", "Xerath",],
      ko: ["아크샨", "아무무", "아지르", "나서스", "람머스", "레넥톤", "렝가", "시비르", "스카너", "탈리야", "제라스",],
      story: "슈리마 제국은 대륙 전체를 다스릴 정도로 번성했던 문명이었습니다. 과거 막강한 신성전사와 초월체 군단을 통해 남부의 여러 민족을 통일했고, 항구적인 평화를 유지했죠.",
      icon: "/rigeon_icon/shurima_crest_icon.png",
      video: "/rigeon_video/shurima-splashvideo.webm",
    },
    {
      name: "타곤",
      champions: ["Aphelios", "AurelionSol", "Diana", "Leona", "Pantheon", "Soraka", "Taric", "Zoe"],
      ko: ["아펠리오스", "아우렐리온 솔", "다이애나", "레오나", "판테온", "소라카", "타릭", "조이"],
      story: "타곤 산은 룬테라에서 가장 거대한 산으로, 햇살 아래 단련된 이 장대한 바위산에는 룬테라의 최고봉이 한데 모여 있다. 문명에서 멀리 떨어진 이곳은 완전히 외딴 곳으로, 지독한 끈기의 소유자가 아니라면 접근조차 불가능한 땅이다. 타곤 산에는 수없이 많은 전설이 깃들어 있으며 전설에 회자되는 장소가 다 그러하듯, 타곤 산에도 몽상가와 미치광이, 모험가가 몰려든다.",
      icon: "/rigeon_icon/mount_targon_crest_icon.png",
      video: "/rigeon_video/mount-targon-splashvideo.webm",
    },
    {
      name: "프렐요드",
      champions: ["Anivia", "Ashe", "Braum", "Gnar", "Gragas", "Lissandra", "Nunu", "Olaf", "Ornn", "Sejuani", "Trundle", "Tryndamere", "Udyr", "Volibear"],
      ko: ["애니비아", "애쉬", "브라움", "나르", "그라가스", "리산드라", "누누", "올라프", "오른", "세주아니", "트런들", "트린다미어어", "우디르", "볼리베어"],
      story: "프렐요드는 혹독하고 가차 없는 기후의 땅입니다. 이곳 주민들은 태어날 때부터 전사이며, 극악의 환경 속에서 살아남아야 합니다. 긍지와 독립심이 대단한 이곳 사람들은 발로란 전역의 이웃들로부터 질서 없고, 거칠고, '야만적'이라 불리곤 합니다.그러나 이것은 프렐요드의 문화를 창조한 고대 전통을 이해하지 못한 데서 생긴 편견입니다.수천 년 전, 세 자매 아바로사, 세릴다, 리산드라 사이의 동맹이 룬테라 전체를 소리 없이 위협한 전쟁으로 인해 깨졌습니다.이로 인해 북쪽 땅은 혼돈과 끝날 줄 모르는 겨울에 잠식되었습니다.",
      icon: "/rigeon_icon/freljord_crest_icon.png",
      video: "/rigeon_video/freljord-splashvideo.webm",
    },
    {
      name: "공허",
      champions: ["Belveth", "Chogath", "Kaisa", "Kassadin", "Khazix", "KogMaw", "Malzahar", "RekSai", "Velkoz"],
      ko: ["벨베스", "초가스", "카이사", "카사딘", "카직스", "코그모", "말자하", "렉사이", "벨코즈"],
      story: "이 우주가 탄생하던 날, 공허도 함께 생겨났다. 우주 너머에 자리한, 우리가 알 수 없는 ‘무’의 표상으로서. 공허는 채워지지 않는 허기의 힘이며, 그 주인인 미지의 주시자들이 마지막 파멸의 시간을 알리기를 기다리며 영겁의 세월을 보내고 있다.",
      icon: "/rigeon_icon/void_crest_icon.png",
      video: "/rigeon_video/void-splashvideo.webm",
    },
    {
      name: "자운",
      champions: ["Blitzcrank", "DrMundo", "Ekko", "Janna", "Jinx", "Renata", "Singed", "Twitch", "Urgot", "Viktor", "Warwick", "Zac", "Ziggs", "Zeri",],
      champions: ["블리츠크랭크", "문도 박사", "에코", "잔나", "진", "레나타", "신지드", "트위치", "우르곳", "빅토르", "워윅", "자크", "직스", "제리",],
      story: "자운은 필트오버를 관통하는 깊은 계곡과 골짜기 밑에 자리잡은 거대한 지하도시이다. 그나마 이 밑까지 닿는 희미한 빛도 얼기설기 녹슨 배관에서 나오는 매연에 흐려지고 공업 시설물을 덮은 스테인드글라스에 반사되어 색색으로 물든다. 자운과 필트오버는 원래 한 도시였고, 갈라선 지금도 공생 관계를 유지하고 있다. 자운은 번성하는 도시로, 언제나 스모그 가득한 어스름에 덮여있지만 주민들은 활기차며 문화는 융성하다.",
      icon: "/rigeon_icon/zaun_crest_icon.png",
      video: "/rigeon_video/zaun-splashvideo.webm",
    },
  ]
}